channels:
  - openbabel
  - rdkit
  - anaconda
  - conda-forge
  - e3sm
  - eumetsat
  - schrodinger
  - pytorch
  - plotly
  - dglteam
dependencies:
  - python=3.7
  - pytorch==1.8.*
  - cudatoolkit=10.2
  - dgl-cuda10.2
  #- pytorch-lightning==1.2.* #==1.2  # this line causes conflict
  - numpy=1.*
  - scipy==1.*
  - griddataformats==0.*
  - mdtraj==1.9.*
  - networkx==2.4.*
  - pymol==2.3.*
  - openbabel=2.4
  - pandas
  - click
  #- scikit-learn
  - pytest
  - plotly
  - rdkit
  - matplotlib
  - seaborn
  - tqdm
  - path.py
  - ipykernel
